{% set name = "kelp-o-matic" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f5156747a574e92160307d555052a71ba1009648b4d00795ca368bed03fb953

build:
  entry_points:
    - kom = kelp_o_matic.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9, <3.12
    - poetry-core
    - pip
  run:
    - python ~=3.9, <3.12
    - numpy ~=1.24.2
    - pytorch ~=2.1.0
    - fsspec
    - rasterio ~=1.3.7
    - rich ~= 13.5.0
    - torchvision ~=0.16.1
    - typer ~=0.9.0
  run_constrained:
    - pytorch-cuda >=11.8

test:
  imports:
    - kelp_o_matic
    - kelp_o_matic.geotiff_io
  commands:
    - pip check
    - kom --help
  requires:
    - pip

about:
  home: https://github.com/HakaiInstitute/kelp-o-matic
  summary: Segmentation Tools for Remotely Sensed RPAS Imagery
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://kelp-o-matic.readthedocs.io
  dev_url: https://github.com/HakaiInstitute/kelp-o-matic

extra:
  recipe-maintainers:
    - tayden
