{% set name = "kelp-o-matic" %}
{% set version = "0.13.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a0e5b9a799e69a6284ea341b208ac5c9a0aa1832c9f9724df0c80925d9e46d43

build:
  entry_points:
    - kom = kelp_o_matic.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24.2
    - pytorch >=2.1.0, <3
    - fsspec
    - rasterio >=1.3.7, <2
    - rich >=13.5, <14
    - torchvision ~=0.16.1
    - typer ~=0.9.0
    - packaging >=24.1, <25
  run_constrained:
    - pytorch-cuda >=11.8

test:
  imports:
    - kelp_o_matic
    - kelp_o_matic.geotiff_io
  commands:
    - pip check
    - kom --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/HakaiInstitute/kelp-o-matic
  summary: Segmentation Tools for Remotely Sensed RPAS Imagery
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://kelp-o-matic.readthedocs.io
  dev_url: https://github.com/HakaiInstitute/kelp-o-matic

extra:
  recipe-maintainers:
    - tayden
