{% set name = "kelp-o-matic" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kelp-o-matic-{{ version }}.tar.gz
  sha256: d7979f0f930e47bcd893eeaa80de265344cea00acea90b98feef3c458d173127

build:
  entry_points:
    - kom = kelp_o_matic.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - typer >=0.4,<1.dev0
    - numpy >=1.16,<2.dev0
    - pytorch >=1.10,<2.dev0
    - rasterio >=1.2,<2.dev0
    - torchvision >=0.11,<1.dev0
    - tqdm >=4.62,<5.dev0

test:
  imports:
    - kelp_o_matic
    - kelp_o_matic.data
    - kelp_o_matic.geotiff_io
  commands:
    - pip check
    - kom --help
  requires:
    - pip

about:
  home: https://github.com/HakaiInstitute/kelp-o-matic
  summary: Segmentation Tools for Remotely Sensed RPAS Imagery
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://kelp-o-matic.readthedocs.io
  dev_url: https://github.com/HakaiInstitute/kelp-o-matic

extra:
  recipe-maintainers:
    - tayden
